runmode: release                 # 开发模式, debug, release, test
addr: :8013                 # HTTP绑定端口
name: rzc-game              # API Server的名字
url: http://127.0.0.1:8013   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
db:
  name: blog
  host: 127.0.0.1:3306
  username: root
  password: 111111
  charset: utf8mb4
redis:
  host: 127.0.0.1
  port: 6379
  auth: 
integral_url: http://127.0.0.1:9501